#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

GEM_RUBY_VERSION = "$(cat .ruby-version)"
PATH_RUBY_VERSION = "$(ruby --version | cut -d' ' -f 2)"
if [ "$PATH_RUBY_VERSION" != "$GEM_RUBY_VERSION" ]; then
  echo "WARNING: The version of ruby currently in the $$PATH is $PATH_RUBY_VERSION but this gem uses $GEM_RUBY_VERSION"
  echo "         Consider installing version $GEM_RUBY_VERSION by running 'rbenv install $GEM_RUBY_VERSION'"
fi

script/bootstrap
