#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  bundle exec rspec "$1"
else
  bundle exec rspec && rspec_exit=$? || rspec_exit=$?
  cat "./coverage/coverage.txt"
  grep -q "You're all set, friend" "./coverage/coverage.txt" && cov_exit=0 || cov_exit=1

  echo ""
  echo "---------------------------------------"
  echo "Summary Results"
  echo "---------------------------------------"
  echo ""
  echo "rspec:       exitcode=${rspec_exit}"
  echo "coverage:    exitcode=${cov_exit}"

  [ $rspec_exit -gt 0 ] && exit 1
  [ $cov_exit -gt 0 ] && exit 1
  exit 0
fi